sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: r1KsgeKfi8LPiLQyOupX7gDNVzFTdfvSAc+cboF9ay9KD4wAERGUAWBvrxS0PYL+bGI8ean6eCxW2KOP3faEQa63YhtA0LGm/bxnhuC2TUtGsaYY89Fq0qfDH/+69vyZnnmaOzMOmQko1mWpE1UpOou14HTDdcTveO72AZZcQ4vOdSPz6QqJzXpx7KV7e5MDG0szztU5DwabSSndf4j8AUFXApUAbxYNdR/DjQnsbFAU3nCABN1+txJQjbPu23xZ4p8bMyQpSHGmwx6DgMtCL3Ik3hSltIVllgO/s8Nz56t7AzVpmDYvzng+kZegLVHCAaSXVJYwhURwVykn217A+67nYKeaV0kvojxVAJGe35VpdZPl198z7E22m9d/jE94pnwyuFjGYJFmkxXA9dR5o87z8Tb9coIs7DHNNmAK5y+REF19kzJr7+yV8My5aQmmCe7pqGXEU7iTqEnlqPUybZ+RhhrzcSXhe6HTRwUkYy3R+4vMQc16KmkE1sXXhnta46YH2WuIFDArAz6vy+o1/f3g4ykCUgGoWZeg3pg8stFQaAQnxPSOecFgCic9ifYk4W95xEkpzWWV3p+x5ZxTddLHvQBIEbQegV0u+/hjKJWaqLH9x/jX1+CVX9aPasZtBvvTv+xeIFWlel1M3n2dxbiZJZj/KD9lJRmH1OZWQ3s=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Buch-der-Lieder_3498
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy